parameters:
- name: configuration
  displayName: Build Configuration
  type: string
  default: Release
  values:
  - Debug
  - Release
- name: beta
  displayName: Beta
  type: boolean
  default: false
  values:
  - true
  - false

trigger:
  batch: true
#  branches:
#    include:
#      - master

pool:
  vmImage: 'windows-2022'

variables:
  solution: 'DPackRx.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: ${{ parameters.configuration }}

name: "DPackRx.$(Date:yyyyMMdd).$(Build.BuildID)"
steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    verbosityRestore: 'Quiet'

- task: VSBuild@1
  inputs:
    vsVersion: '17.0'
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '-verbosity:minimal -p:DeployExtension=false -p:BETA=${{ parameters.beta }}'

- task: VSTest@2
  inputs:
    vsTestVersion: 'latest'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: |
      **/bin/$(buildConfiguration)/*.Tests.dll

- task: CopyFiles@2
  inputs:
    contents: |
      DPackRx/bin/$(buildConfiguration)/DPackRx-*.vsix
      .azure/vsix-publish-manifest.json
      .azure/vsix-readme.md
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    overWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'DPackRx'
